project:
  type: website
  output-dir: docs

website:
  title: "Modelos Lineares -- Prova 3"
  navbar:
    background: primary
    search: true
    right: 
      - icon: github
        href: https://github.com/cesar-galvao/modelos_lineares
    body-footer: "César A. Galvão, 2022"
    
  sidebar: 
    - title: "Prova 3"
      style: "docked"
      contents: 
      - questao1.qmd
      - questao2.qmd


format:
  html:
    fig-align: "center"
    code-fold: true
    code-summary: "Show the code"
    theme: flatly
    css: styles.css
    toc: true
    toc-title: Conteúdo
    toc-expand: true
    html-math-method: katex
    code-overflow: wrap
    code-copy: true


execute:
  freeze: auto



